// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqltxewtjwzlqdicuahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbHR4ZXd0and6bHFkaWN1YWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDY1ODYsImV4cCI6MjA2MjE4MjU4Nn0.DCR-ULcN4iDo5-mzoyx9CvIMldr19oOo8o40G75Eljc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);